admin_search_index:
  path: /
  methods: [ GET ]
  defaults:
    _controller: PrestaShopBundle\Controller\Admin\Configure\ShopParameters\SearchController::indexAction
    _legacy_controller: AdminSearchConf
    _legacy_link: AdminSearchConf
    _legacy_feature_flag: search_conf

admin_alias_search:
  path: /
  methods: [ POST ]
  defaults:
    _controller: PrestaShopBundle\Controller\Admin\CommonController::searchGridAction
    gridDefinitionFactoryServiceId: PrestaShop\PrestaShop\Core\Grid\Definition\Factory\AliasGridDefinitionFactory
    redirectRoute: admin_search_index
    _legacy_controller: AdminSearchConf
    _legacy_link: AdminSearchConf:submitFilteralias
    _legacy_feature_flag: search_conf

admin_alias_search_search_term_action:
  path: /
  methods: [ GET, POST ]
  defaults:
    _controller: PrestaShopBundle\Controller\Admin\Configure\ShopParameters\SearchController::searchAliasesForAssociationAction
    _legacy_controller: AdminSearchConf
